name: Build R image
run-name: ${{ github.actor }} is testing this assignment solution
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - run: docker build -t ghcr.io/bf591-r/bf591-r-docker .
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - run: docker push ghcr.io/bf591-r/bf591-r-docker:latest
      


