name: Build R image
run-name: ${{ github.actor }} is testing this assignment solution
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - run: docker build -t bf591-r-docker .
      - run: docker push ghcr.io/BF591-R/bf591-r-docker:latest


